services:
  work:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    ipc: host
    privileged: true
    volumes:
      - .:/work
    working_dir: /work
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/work
      - NVIDIA_VISIBLE_DEVICES=0
    ulimits:
      memlock: -1
      stack: 67108864
    command: /bin/bash -c "ln -sf /usr/bin/python3.10 /usr/bin/python && python setup.py build_ext --inplace && /bin/bash"
